    name: PHP 5.6 Test

    on: [push]

    jobs:
      build:
        name: Check
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v1
            with:
              fetch-depth: 0
          - name: PHP Syntax Checker (Lint) 5.6
            uses: StephaneBour/actions-php-lint@5.6
            with:
              dir: './src/dslc/'