    name: PHP 7.0 Test

    on: [push]

    jobs:
      build:
        name: Check
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v1
            with:
              fetch-depth: 0
          - name: PHP Syntax Checker (Lint) 7.0
            uses: StephaneBour/actions-php-lint@7.0
            with:
              dir: './src/dslc/'